[phases.setup]
nixPkgs = ["python311", "gcc", "libGL", "libGLU", "xorg.libX11", "ffmpeg"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT src.api.main:app"

[variables]
PYTHONUNBUFFERED = "1"
